# Generated by Django 5.0.6 on 2024-07-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mesAnalizado', models.CharField(max_length=50)),
                ('fechaPublicacion', models.DateField()),
            ],
        ),
    ]
